### ISSUE TITLE
Description of serial format is not accurate

### ISSUE THREAD

**Issue by cdelargy** [hackerschoice/thc-tesla-powerwall2-hack#7]
> The serial number looks like this:
> 
> ST\<YY\>\<L\>0001\<XYZ\>
> YY is the built year and L is the revision number. I’ve seen revisions with letter D through to I. For example ST17H0001789 would be a valid password for the Tesla PW on a WiFi network with SSID TEG-789.

Not reproducible on my unit.

Last three alphanumeric characters of serial match the SSID, as documented on https://www.tesla.com/support/energy/powerwall/own/monitoring-from-home-network

There are at least 3 substring errors in the stated serial format on ours. The first two chars match, YY is not in the same position, revision doesn't fit your format. 0001 appears static.

**Comment by rootTHC** [comment]
Is this related to the Backup Gateway or the standard Gateway? The Backup Gateway uses a different format for the Serial and the wifi password is written on the inside of the lid. I'm not sure how random that one is though...looks more random.
